### ISSUE TITLE
issue with netvars

### ISSUE THREAD

**Issue by Bam810bam321** [clouddss/cs2-internal-sdk#2]
When injecting you will get this issue with the netvars I am fixing it right now just wanted to inform you guys about it
![image](https://github.com/clouddss/cs2-internal-sdk/assets/67829250/0f690cd5-b91b-438a-90ed-5cac0f5d9922)

**Comment by HeitorBarella** [comment]
0x10000000018 most of time means nullpointers or when you hit something you wasn't supposed to (smth out of bounds from an array).

And what is causing that is probably because the element gets set to the next element even if the element is the last in the array... which will cause an out of bounds issue. (translating the loop: copy unallocated_data to element var, if the element is not null then we will set the element to the next one. See the problem, once we arrive at the last element the element still isn't null so we will set it to the next element which will cause out of bounds)

```cpp
if (element == nullptr) 
    break;
```
Add the code above and you should be fine^^
